joeshop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from vitashop.views import index, affil_index
# from django.conf.urls import handler404, handler500, handler403, handler400
from vitashop.views import error404, error500, error403, error400

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^(?P<slug>[^/]+)$', affil_index, name='affil'),
    url(r'^$', index, name='shop_welcome'),
    url(r'', include('web.urls')),
    url(r'^shop/', include('vitashop.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'^shop/', include('shop.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = error404
handler500 = error500
handler403 = error403
handler400 = error400

vitashop/urls.py
from django.conf.urls import patterns, url, include
from shop.util.decorators import cart_required
from django.contrib.auth.decorators import login_required
from vitashop.views import *
from vitashop.forms import ValidatingPasswordChangeForm
from shop.views.cart import CartDetails, CartItemDetail
from django.contrib.auth.views import password_change, password_change_done
from vitashop.views_checkout import *


urlpatterns = patterns('vitashop.views',
    url(r'^$', index, name='shop_welcome'),
    url(r'^error/', error_view, name='error'),
    url(r'^test/', test_view, name='test'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
    url(r'^register/success', register_success_view, name='register_success'),
    url(r'^activate/(?P<code>[0-9A-Za-z-_=.]+)$', activate_view, name='activate'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^changepwd/$', password_change, {'template_name': 'vitashop/change_pwd.html',
         'password_change_form': ValidatingPasswordChangeForm}, name='password_change'),
    url(r'^changepwd/done/$', password_change_done, {'template_name': 'vitashop/change_pwd_done.html'},
                                                                name='password_change_done'),

    url(r'^setpwd/$', password_set, name='password_set'),

    url(r'^exchange/$', exchange, name='exchange'),
    url(r'^products/$', products, name='products'),
    url(r'^currency/$', currency, name='currency'),
    url(r'^products/(?P<slug>[0-9A-Za-z-_.//]+)/$', product_detail, name='product_detail'),

    url(r'^cart/$', MyCartDetails.as_view(), name='cart'),
    url(r'^cart/delete/$', MyCartDetails.as_view(action='delete'), name='cart_delete'),
    url(r'^cart/item/$', MyCartDetails.as_view(action='post'), name='cart_item_add'),
    url(r'^cart/update/$', MyCartDetails.as_view(action='put'), name='cart_update'),

    # CartItems
    url(r'^cart/item/(?P<id>[0-9]+)$', CartItemDetail.as_view(), name='cart_item'),
    url(r'^cart/item/(?P<id>[0-9]+)/delete$', CartItemDetail.as_view(action='delete'), name='cart_item_delete'),

    # checkout
    #url(r'^checkout/ship/flat/$', PaymentBackendRedirectView.as_view(), name='flat'),
    #url(r'^checkout/pay/pay-on-delivery/$', PaymentBackendRedirectView.as_view(), name='pay-on-delivery'),
    #url(r'^checkout/pay/advance-payment/$', PaymentBackendRedirectView.as_view(), name='advance-payment'),

    url(r'^checkout/pay/', include('shop.payment.urls')),
    url(r'^checkout/ship/', include('shop.shipping.urls')),
    url(r'^checkout/wallet', wallet, name='wallet'),

    #url(r'^checkout/ship/$', ShippingBackendRedirectView.as_view(), name='checkout_shipping'),  # second step
    #url(r'^checkout/pay/$', PaymentBackendRedirectView.as_view(), name='checkout_payment'),  # fourth step

    url(r'^checkout/$', login_required(cart_required(MyCheckoutSelectionView.as_view())), name='checkout_selection'),  # first step
    url(r'^methods/$', login_required(cart_required(CheckoutMethodsView.as_view())), name='checkout_methods'),
    url(r'^overview/$', login_required(cart_required(OverviewView.as_view())), name='checkout_overview'),
    url(r'^checkout/thank_you/$', ThankYouView.as_view(), name='checkout_thankyou'),  # final step

    url(r'^checkout/ppsuccess', pp_success_page, name='ppsuccess'),
    url(r'^checkout/ppcanceled', pp_canceled_page, name='ppcanceled'),
    url(r'^checkout/ppfailed', pp_failed_page, name='ppfailed'),

    url(r'^orders/(?P<id>\d+)/$', OrderDetailView.as_view(), name='vita_order_detail'),

)

web/urls.py
from django.conf.urls import patterns, url, include
from shop.util.decorators import cart_required
from django.contrib.auth.decorators import login_required
from vitashop.views import *
from vitashop.forms import ValidatingPasswordChangeForm
from shop.views.cart import CartDetails, CartItemDetail
from django.contrib.auth.views import password_change, password_change_done
from web.views import *


urlpatterns = patterns('web.views',
    url(r'^contact/', contact_view, name='contact'),
    url(r'^information/', information_view, name='information'),
    url(r'^bitcoins/', bitcoin_view, name='bitcoin'),
    url(r'^faq/', faq_view, name='faq'),
    url(r'^affiliate/', affiliate_view, name='affiliate'),
    url(r'^thankyou/', thankyou_view, name='thankyou'),
    url(r'^fbtest/', fbtest_view, name='fbtest'),
)

shop/models/ordermodel.py
# -*- coding: utf-8 -*-
from distutils.version import LooseVersion
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_delete
from django.utils.translation import ugettext_lazy as _
from jsonfield.fields import JSONField
from shop.models.productmodel import Product
from shop.util.fields import CurrencyField
from shop.util.loader import load_class
import django


#==============================================================================
# Extensibility
#==============================================================================
# This overrides the various models with classes loaded from the corresponding
# setting if it exists.

# Order model
ORDER_MODEL = getattr(settings, 'SHOP_ORDER_MODEL',
    'shop.models.defaults.order.Order')
Order = load_class(ORDER_MODEL, 'SHOP_ORDER_MODEL')

# Order item model
ORDERITEM_MODEL = getattr(settings, 'SHOP_ORDERITEM_MODEL',
    'shop.models.defaults.orderitem.OrderItem')
OrderItem = load_class(ORDERITEM_MODEL, 'SHOP_ORDERITEM_MODEL')


# Now we clear refrence to product from every OrderItem
def clear_products(sender, instance, using, **kwargs):
    for oi in OrderItem.objects.filter(product=instance):
        oi.product = None
        oi.save()

if LooseVersion(django.get_version()) < LooseVersion('1.3'):
    pre_delete.connect(clear_products, sender=Product)


class OrderExtraInfo(models.Model):
    """
    A holder for extra textual information to attach to this order.
    """
    order = models.ForeignKey(Order, related_name="extra_info",
            verbose_name=_('Order'))
    text = models.TextField(verbose_name=_('Extra info'), blank=True)

    class Meta(object):
        app_label = 'shop'
        verbose_name = _('Order extra info')
        verbose_name_plural = _('Order extra info')


class ExtraOrderPriceField(models.Model):
    """
    This will make Cart-provided extra price fields persistent since we want
    to "snapshot" their statuses at the time when the order was made
    """
    order = models.ForeignKey(Order, verbose_name=_('Order'))
    label = models.CharField(max_length=255, verbose_name=_('Label'))
    value = CurrencyField(verbose_name=_('Amount'))
    data = JSONField(null=True, blank=True, verbose_name=_('Serialized extra data'))
    # Does this represent shipping costs?
    is_shipping = models.BooleanField(default=False, editable=False,
            verbose_name=_('Is shipping'))

    class Meta(object):
        app_label = 'shop'
        verbose_name = _('Extra order price field')
        verbose_name_plural = _('Extra order price fields')


class ExtraOrderItemPriceField(models.Model):
    """
    This will make Cart-provided extra price fields persistent since we want
    to "snapshot" their statuses at the time when the order was made
    """
    order_item = models.ForeignKey(OrderItem, verbose_name=_('Order item'))
    label = models.CharField(max_length=255, verbose_name=_('Label'))
    value = CurrencyField(verbose_name=_('Amount'))
    data = JSONField(null=True, blank=True, verbose_name=_('Serialized extra data'))

    class Meta(object):
        app_label = 'shop'
        verbose_name = _('Extra order item price field')
        verbose_name_plural = _('Extra order item price fields')


class OrderPayment(models.Model):
    """
    A class to hold basic payment information. Backends should define their own
    more complex payment types should they need to store more informtion
    """
    order = models.ForeignKey(Order, verbose_name=_('Order'))
    # How much was paid with this particular transfer
    amount = models.DecimalField(max_digits=11, decimal_places=4, default=0, verbose_name=_('Amount'))
    transaction_id = models.CharField(max_length=255,
            verbose_name=_('Transaction ID'),
            help_text=_("The transaction processor's reference"))
    payment_method = models.CharField(max_length=255,
            verbose_name=_('Payment method'),
            help_text=_("The payment backend used to process the purchase"))

    class Meta(object):
        app_label = 'shop'
        verbose_name = _('Order payment')
        verbose_name_plural = _('Order payments')

vitashop/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm as DjangoAuthenticationForm, PasswordResetForm
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from shop.addressmodel.models import Address, Country
from shop.forms import get_shipping_backends_choices, get_billing_backends_choices
from vitashop.models import Customer, MyUser
from django.contrib import auth


class SetPasswordForm(forms.Form):
    MIN_LENGTH = 4
    new_password1 = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Set New Password'}))

    def clean_new_password1(self):
        data = self.cleaned_data['new_password1']
        if len(data) < self.MIN_LENGTH:
            raise forms.ValidationError("The new password must be at least %d characters long." %
                                        self.MIN_LENGTH)

        # At least one letter and one non-letter
        first_isalpha = data[0].isalpha()
        if all(c.isalpha() == first_isalpha for c in data):
            raise forms.ValidationError("The new password must contain at least one letter and "
                                        "at least one digit or punctuation character.")
        return data


class ValidatingPasswordChangeForm(auth.forms.PasswordChangeForm):
    MIN_LENGTH = 4
    def clean_new_password1(self):
        data = self.cleaned_data['new_password1']
        if len(data) < self.MIN_LENGTH:
            raise forms.ValidationError("The new password must be at least %d characters long." %
                                        self.MIN_LENGTH)

        # At least one letter and one non-letter
        first_isalpha = data[0].isalpha()
        if all(c.isalpha() == first_isalpha for c in data):
            raise forms.ValidationError("The new password must contain at least one letter and "
                                        "at least one digit or punctuation character.")
        return data


class RegistrationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    MIN_LENGTH = 4
    error_messages = {
        'duplicate_email': _("A user with that email already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    email = forms.EmailField(label=_("Email"), max_length=50, help_text=_("Required. "),
        error_messages={'invalid': _("This value must be valid email address.")})
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above, for verification."))
    language = forms.HiddenInput()

    class Meta:
        model = MyUser
        fields = ("email",)

    def clean_email(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM.
        email = self.cleaned_data["email"]
        try:

            self.Meta.model.objects.get(email=email)
        except self.Meta.model.DoesNotExist:
            return email.lower()
        raise forms.ValidationError(
            self.error_messages['duplicate_email'],
            code='duplicate_username',
        )

    def clean_password1(self):
        data = self.cleaned_data['password1']
        if len(data) < self.MIN_LENGTH:
            raise forms.ValidationError("The new password must be at least %d characters long." %
                                        self.MIN_LENGTH)

        # At least one letter and one non-letter
        first_isalpha = data[0].isalpha()
        if all(c.isalpha() == first_isalpha for c in data):
            raise forms.ValidationError("The new password must contain at least one letter and "
                                        "at least one digit or punctuation character.")
        return data

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        self.clean_password1()
        password = self.clean_password2()
        email = self.clean_email()
        username = email
        username = username.replace('+', '')
        username = username.replace('@', '.')
        user = self.Meta.model.objects.create_inactive_user(email, username, password)
        return user


class AuthenticationForm(DjangoAuthenticationForm):
    username = forms.CharField(max_length=254, widget=forms.TextInput(attrs={'placeholder': 'email'}))
    password = forms.CharField(label=_("Password"), widget=forms.PasswordInput(attrs={'placeholder': 'password'}))
    next = forms.HiddenInput()

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        self.cleaned_data = {}

    def clean_username(self):
        username = self.cleaned_data.get("username")
        return username

    def clean_password(self):
        password = self.cleaned_data.get("password")
        return password

    def clean_next(self):
        next = self.cleaned_data.get("next")
        return next

class CaptchaLoginForm(AuthenticationForm):
    # captcha = CaptchaField()
    pass


class ProfileForm(forms.ModelForm):

    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name')


class CustomerForm(forms.ModelForm):
    Language_CHOICES = settings.LANGUAGES
    Currency_CHOICES = (('CZK', 'CZK'), ('USD', 'USD'))
    language = forms.ChoiceField(label=_("Language"),
                                 widget=forms.Select(attrs={'class': 'form-control'}),
                                 choices=Language_CHOICES)
    currency = forms.ChoiceField(label=_("Currency"),
                                 widget=forms.Select(attrs={'class': 'form-control'}),
                                 choices=Currency_CHOICES)
    class Meta:
        model = Customer
        fields = ('language', 'currency', 'has_newsletter', 'affiliate')


class ChangePasswordForm(forms.ModelForm):

    class Meta:
        model = MyUser
        fields = ('first_name', 'last_name',)


class CountryForm(forms.ModelForm):

    class Meta:
        model = Country
        fields = ('name',)

class CzechAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('name', 'address', 'city', 'zip_code', 'country')


class USAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ('name', 'address', 'address2', 'city', 'zip_code', 'state', 'country')


class ShippingForm(forms.Form):
    """
    A form displaying all available payment and shipping methods (the ones
    defined in settings.SHOP_SHIPPING_BACKENDS and
    settings.SHOP_PAYMENT_BACKENDS)
    """
    shipping_method = forms.ChoiceField(choices=get_shipping_backends_choices(), label=_('Shipping method'))



class BillingForm(forms.Form):
    """
    A form displaying all available payment and shipping methods (the ones
    defined in settings.SHOP_SHIPPING_BACKENDS and
    settings.SHOP_PAYMENT_BACKENDS)
    """
    payment_method = forms.ChoiceField(choices=get_billing_backends_choices(), label=_('Payment method'))

vitashop/templates/vitashop/cart.html
{% extends "vitashop/base.html" %}
{% load i18n %}
{% load currency %}
{% load url from future %}

{% block body %}

     <div class="row">
        <div class="btn-group">
          <h3 class="products-header-top">{% trans "Shopping cart" %}:</h3>
        </div>
        <div id="curr-wrapper" class="btn-group pull-right">
            <form action="{% url 'currency' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="cart">
                <div class="float-left">
                    <label for="id_currency">{% trans "Currency" %}:</label>
                    <select id="id_currency" name="sel_currency" class="form-control" onchange="this.form.submit()">
                        {% for c in currency_set %}
                            {% if c == currency %}
                                <option value="{{ c }}" selected>{{ c }}</option>
                            {% else %}
                                <option value="{{ c }}">{{ c }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div>
     </div>

    <div class="row">&nbsp;</div>


  {% if cart_items %}<br  />

    <div class="clearfix"></div>

    <div class="row">
        <div id="cart-panel" class="panel panel-primary col-md-8 col-md-offset-2">

          <div class="panel-heading text-right">
              <form action="{% url 'cart_delete' %}" method="post">
                {% csrf_token %}<span class="panel-title">
                <input type="submit" value="{% trans "Empty Shopping Cart" %}" class="btn btn-default" /></span>
              </form>
          </div>
          <div class="panel-body">

                <form method="post" action="{% url 'cart_update' %}">
                {% csrf_token %}
                {{ formset.management_form }}
                <table id="cartbill" border="1" class="table table-striped table-hover">
                  <thead>
                    <tr>
                    <th>{% trans "Product name" %}</th>
                    <th>{% trans "Unit price" %}</th>
                    <th>{% trans "Quantity" %}</th>
                    <th>{% trans "Price" %}</th>
                    </tr>
                  </thead>

                  <tbody>
                    {% for form in formset %}
                      {% with form.quantity as field %}
                        <tr>
                          <td>{{ form.instance.product.get_name }}</td>
                          <td>{% currency_tag form.instance.product.get_price currency %}</td>
                          <td>
                              {{ form.id }}
                              {{ field.errors }}
                              {{ field }}</td>
                          <td>{% currency_tag form.instance.line_subtotal currency %}</td>
                        </tr>
                        {% for extra_price_field in form.instance.extra_price_fields %}
                          <tr>
                            <td colspan="2">&nbsp;</td>
                            <td>{{ extra_price_field.0 }}</td>
                            <td>{{ extra_price_field.1 }}</td>
                          </tr>
                        {% endfor %}
                          {% if form.instance.extra_price_fields %}
                            <tr>
                                <td colspan="2">&nbsp;</td>
                                <td>{% trans "Line Total" %}:</td>
                                <td>{% currency_tag form.instance.line_total currency %}</td>
                            </tr>
                          {% endif %}
                      {% endwith %}
                    {% endfor %}
                  </tbody>

                  <tfoot>
                    <tr>
                        <td colspan="2">&nbsp;</td>
                        <td>{% trans "Cart Subtotal" %}</td>
                        <td>{% currency_tag cart.total_price currency %}</td>
                    </tr>
                    {% for extra_price_field in cart.extra_price_fields %}
                      <tr>
                        <td colspan="2">&nbsp;</td>
                        <td>{{ extra_price_field.0 }}</td>
                        <td>{% currency_tag extra_price_field.1 currency %}</td>
                      </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="2">&nbsp;</td>
                        <td><b>{% trans "Cart Total" %}</b></td>
                        <td><b>{% currency_tag cart.total_price currency %}</b></td>
                    </tr>
                  </tfoot>
                </table>

                <div class="text-right">
                    <input type="submit" value="{% trans "Update Shopping Cart" %}" class="btn btn-primary" />
                </div>
                </form>
          </div>
        </div>
    </div>

    <div class="clearfix"></div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <div class="row">
          <div class="btnpanel col-md-12 text-center">
              <a href="{% url 'products' %}" class="btn btn-default pull-left">{% trans "Back to shopping" %} </a>
              <a href="{% url 'checkout_selection' %}" class="btn btn-danger btn-md">{% trans "Proceed to checkout" %}</a>
          </div>
    </div>

    <p>&nbsp;</p>

  {% else %}
      <div class="centerDiv">
          <p>
            {% trans "Shopping cart is empty" %}
          </p>
      </div>
  {% endif %}
{% endblock %}

vitashop/templates/vitashop/order_detail.html
{% extends "vitashop/base.html" %}
{% load i18n %}
{% load url from future %}
{% load shop_tags %}
{% load currency %}
{% block body %}

    <div class="page-header">
          <h3 id="container">{% trans "Order" %} {{ order.id }}</h3>
        </div>

    <div class="row">
        <div class="centerDiv">
        <table border="1" class="order">

        {% if is_billing_address_same %}
            <tr>
                <td colspan="2" class="top">{% trans "Customer information" %}</td>
                <td colspan="2">
                    <b>{% trans "Shipping and billing address" %}</b><br/>
                    {{ shipping_address_name }}<br/>
                    {{ shipping_address_street }}<br/>
                    {{ shipping_address_city }}<br/>
                    {{ shipping_address_zip }}<br/>
                    {{ shipping_address_country }}<br/>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2" class="top">{% trans "Customer information" %}</td>
                <td colspan="2">
                    <b>{% trans "Shipping address" %}</b><br/>
                    {{ shipping_address_name }}<br/>
                    {{ shipping_address_street }}<br/>
                    {{ shipping_address_city }}<br/>
                    {{ shipping_address_zip }}<br/>
                    {{ shipping_address_country }}<br/>
                    <br/>
                    <b>{% trans "Billing address" %}</b><br/>
                    {{ billing_address_name }}<br/>
                    {{ billing_address_street }}<br/>
                    {{ billing_address_city }}<br/>
                    {{ billing_address_zip }}<br/>
                    {{ billing_address_country }}<br/>
                    <br/>
                </td>
            </tr>

        {% endif %}
            <tr>
                <td colspan="2">{% trans "Shipping" %}</td>
                <td colspan="2">
                    {{ shipping_backend }}<br/>
                </td>
            </tr>
            <tr>
                <td colspan="2">{% trans "Payment" %}</td>
                <td colspan="2">
                    {{ payment_backend }}<br/>
                </td>
            </tr>

            <tr>
                <td class="header">{% trans "Product name" %}</td>
                <td class="header">{% trans "Unit price" %}</td>
                <td class="header">{% trans "Quantity" %}</td>
                <td class="header text-center">{% trans "Price" %}</td>
            </tr>

            {% for item in order.items.all %}
              <tr>
                <td>{{item.product_name}}</td>
                <td class="text-right">{% currency_tag item.unit_price currency %}</td>
                <td>{{item.quantity}}</td>
                <td class="text-right">{% currency_tag item.line_subtotal currency %}</td>
              </tr>

              {% if item.extraorderitempricefield_set.all %}
                  {% for item_extra in item.extraorderitempricefield_set.all %}
                    <tr>
                      <td colspan="2">&nbsp;</td>
                      <td>{{ item_extra.label }}</td>
                      <td>{{ item_extra.value }}</td>
                    </tr>
                  {% endfor %}

                  <tr>
                      <td colspan="2">&nbsp;</td>
                      <td>{% trans "Line Total" %}:</td>
                      <td class="text-right">{% currency_tag item.line_total currency %}</td>
                  </tr>
                {% endif %}

            {% endfor %}


          <tfoot>
            <tr>
                <td colspan="2">&nbsp;</td>
                <td>{% trans "Order Subtotal" %}</td>
                <td class="text-right">{% currency_tag order.order_subtotal currency %}</td>
            </tr>
            {% for extra_price_field in order.extraorderpricefield_set.all %}
              <tr>
                <td colspan="2">&nbsp;</td>
                <td>{% trans extra_price_field.label|safe %}</td>
                <td class="text-right">{% currency_tag extra_price_field.value currency %}</td>
              </tr>
            {% endfor %}
            <tr>
                <td colspan="2">&nbsp;</td>
                <td><b>{% trans "Order Total" %}</b></td>
                <td class="text-right"><b>{% currency_tag order.order_total currency %}</b></td>
            </tr>
          </tfoot>
        </table>
        </div>
    </div>

    <div class="space40"></div>
    <div class="clearfix"></div>

{% endblock %}

vitashop/templates/vitashop/product_detail.html
{% extends "vitashop/base.html" %}
{% load i18n %}
{% load currency %}
{% load url from future %}
{% block body %}

    <div class="row">
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            {% trans "Products" %} <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            {% for prod in products %}
                <li><a href="{% url 'product_detail' prod.slug %}">{{ prod.name }}</a></li>
            {% endfor %}
          </ul>
        </div>
        <div id="curr-wrapper" class="btn-group pull-right">
            <form action="{% url 'currency' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="product_detail {{ product.slug }} ">
                <div class="float-left">
                    <label for="id_currency">{% trans "Currency" %}:</label>
                    <select id="id_currency" name="sel_currency" class="form-control" onchange="this.form.submit()">
                        {% for c in currency_set %}
                            {% if c == currency %}
                                <option value="{{ c }}" selected>{{ c }}</option>
                            {% else %}
                                <option value="{{ c }}">{{ c }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-sm-5 col-xs-12">

            <div class=" margin-20">
                <img src="/media/products/{{ product.image }}" class="img-responsive" alt="{{ product.name }}" />
            </div>

        </div>
        <div class="col-md-6 col-md-offset-1 col-sm-7 col-xs-12">
            <h2>{{ product.name }}</h2>
            <p>
                <span class="product-price-label">{% trans "Price" %}:</span>
                <span class="product-price">{% currency_tag product.unit_price currency %}</span>
            </p>
            <form method="post" action="{% url 'cart' %}">{% csrf_token %}
                <input type="hidden" name="add_item_id" value="{{product.pk}}">
                <input type="hidden" name="add_item_quantity" value="1">
                <input type="submit" class="btn btn-danger" value="{% trans "Add to Cart" %}" role="button">
            </form>
            <p>    </p>

            <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#info" data-toggle="tab"><span class="hidden-phone">{% trans "Information" %}</span></a></li>
                <li class=""><a href="#facts" data-toggle="tab"><span class="hidden-phone">{% trans "Supplements" %}</span></a></li>
                <li class=""><a href="#use" data-toggle="tab"><span class="hidden-phone">{% trans "Usage" %}</span></a></li>
                <li class=""><a href="#warnings" data-toggle="tab">{% trans "Warnings" %}</a></li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane pad5 active" id="info">

                    {% trans product.desc1|safe %}

                </div>
                <div class="tab-pane pad5" id="facts">

                    {% trans product.desc2|safe %}

                </div>

                <div class="tab-pane pad5" id="use">

                    {% trans product.desc3|safe %}

                </div>
                <div class="tab-pane pad5" id="warnings">

                    {% trans "This product is not intended to diagnose, treat, cure, or prevent any disease." %}

                </div>
              </div>

        </div>
    </div>

{% endblock %}