joeshop/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from vitashop.views import index, affil_index
# from django.conf.urls import handler404, handler500, handler403, handler400
from vitashop.views import error404, error500, error403, error400

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^(?P<slug>[^/]+)$', affil_index, name='affil'),
    url(r'^$', index, name='shop_welcome'),
    url(r'', include('web.urls')),
    url(r'^shop/', include('vitashop.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'^shop/', include('shop.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = error404
handler500 = error500
handler403 = error403
handler400 = error400

web/urls.py
from django.conf.urls import patterns, url, include
from shop.util.decorators import cart_required
from django.contrib.auth.decorators import login_required
from vitashop.views import *
from vitashop.forms import ValidatingPasswordChangeForm
from shop.views.cart import CartDetails, CartItemDetail
from django.contrib.auth.views import password_change, password_change_done
from web.views import *


urlpatterns = patterns('web.views',
    url(r'^contact/', contact_view, name='contact'),
    url(r'^information/', information_view, name='information'),
    url(r'^bitcoins/', bitcoin_view, name='bitcoin'),
    url(r'^faq/', faq_view, name='faq'),
    url(r'^affiliate/', affiliate_view, name='affiliate'),
    url(r'^thankyou/', thankyou_view, name='thankyou'),
    url(r'^fbtest/', fbtest_view, name='fbtest'),
)

web/forms.py
from django import forms
from django.conf import settings


class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)
    email = forms.EmailField(label='Email', max_length=100, required=True)
    subject = forms.CharField(label='Subject', max_length=100, required=True)
    comment = forms.CharField(label='Add a comment', widget=forms.Textarea(), required=True)
    #captcha = CaptchaField()

web/templates/web/affiliate.html
{% extends "vitashop/base.html" %}
{% load url from future %}
{% load i18n %}
{% block body %}

    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 id="container">Informace pro členy provizního programu</h3>
        </div>

        <a name="top#"></a>
        <div class="col-md-8">
            <h4>K proviznímu programu má přístup každý zákazník.</h4>
            <p>Každý zákazník, po zakoupení prvního produktu získává nárok na výhody provizního programu.</p>
            <h4>Jak to funguje?</h4>
            <p>V rámci provizního programu má zákazník nárok na odměny a výhody spojené s prodejem produktů.<br>
                Jedná se zejména o:
                <ul>
                    <li>Vlastní slevový kód, opravňující ke 5% slevě ostatní</li>
                    <li>Odměna z prodeje od zákazníků, jež využijí Váš slevový kód</li>
                    <li>Odměna z prodeje od zákazníků, jež přijdou do eshopu přes Vaše stránky(odkazy)</li>
                    <li>Slevu na další nákupy</li>
                    <li>Možnost využít reklamní materiál</li>
                </ul>

            </p>

            <h4>Vlastní slevový kód</h4>
            <p>
                Vlastní slevový kód najdete na stránce profilu. Je to 5-ti místný kód, opravňující zákazníka k 5% slevě na celý nákup po odečtení poštovného.
            </p>

            <h4>Odměny provizního programu</h4>
            <p>
                Pokud zákazník využije při nákupu Váš slevový kód, vy získáte <span class="btc-price">odměnu 5%</span> z ceny objednávky po odečtení poštovného.<br><br>
                Pokud zákazník přijde do eshopu z Vašeho odkazu na eshop bez slevového kupónu a jedná se o nového zákazníka, vy získáte <span class="btc-price">odměnu 10%</span> z ceny objednávky po odečtení poštovného.
                Tento zákazník se připíše k Vašemu účtu a náleží Vám i odměna z jeho dalších nákupů - a to ve výši <span class="btc-price">5%</span> vždy z ceny objednávky po odečtení poštovného.
                Odměny za zákazníka Vám náleží bez časového omezení. Odměny vyplácíme vždy koncem roku. Odměna bude vyplacena pouze v případě, že se bude jednat o částku vyšší než 300Kč. V opačném případě bude převedena do dalšího roku.
            </p>

            <b>Stručně</b>
            <ul>
                <li>10% za prodej novému zákazníkovi</li>
                <li>5% za opakovaný prodej</li>
                <li>nárok na odměnu bez časového omezení</li>
                <li>výplaty na konci roku od 300Kč</li>
                <li>sleva na vlastní nákupy 5%</li>
            </ul>
            <p> </p>
            <h4>Příklad 1 - přes web</h4>
            <p>Zákazník při prohlížení internetu narazí na Vaše stránky s odkazem na tento eshop. Klikne na odkaz a nakoupí produkty v hodnotě 1000Kč.
                Náš systém automaticky propojí jeho účet s Vaším účtem. Pokud on nakoupí, Vám přijde upozornění emailem. Z ceny jím zakoupeného zboží se Vám naúčtuje odměna 10%.
                Zákazník nakoupil za 1000Kč. Vaše odměna je 100Kč. Pokud ten stejný zákazník provede další nákup, náleží Vám odměna 5% za opakovaný nákup, tj. 50Kč. Řekněme, že tento
                zákazník nakupuje pravidelně a během roku uskutečnil 6 nákupů, vždy v hodnotě 1000Kč. Pak výše Vaší odměny za tohoto jednoho zákazníka bude 1x100 + 5x50Kč = 350Kč.
            </p>

            <h4>Příklad 2 - přes slevový kód</h4>
            <p>Zákazník od Vás dostane slevový kód na 5% slevu, který použije při nákupu. Nakoupí produkty v hodnotě 1000Kč.
                Náš systém automaticky propojí jeho objednávku s Vaším účtem. Pokud on nakoupí, Vám přijde upozornění emailem. Z ceny jím zakoupeného zboží se Vám naúčtuje odměna 5%.
                Zákazník nakoupil za 1000Kč. Vaše odměna je 50Kč za tento prodej. Váš slevový kód umožňuje čerpat 5% slevu bez časového omezení. To znamená, že získáte 5% odměnu i za všechny budoucí objenávky od tohoto zákazníka.
            </p>

            <div class="clearfix"></div>

        </div>

        <div class="col-md-4">  </div>
        

        <div class="clearfix"></div>
        <br />
        <br />
      </div>
    </div>

{% endblock %}

web/templates/web/bitcoin.html
{% extends "vitashop/base.html" %}
{% load url from future %}
{% load i18n %}
{% block body %}

    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 id="container">Bitcoins</h3>
        </div>

        <a name="top#"></a>
        <div class="col-md-8">
            <h4>Bitcoins</h4>
            <p>TODO</p>

            <div class="clearfix"></div>

        </div>

        <div class="col-md-4">  </div>
        

        <div class="clearfix"></div>
        <br />
        <br />
      </div>
    </div>

{% endblock %}

web/templates/web/contact.html
{% extends "vitashop/base.html" %}
{% load url from future %}
{% load widget_tweaks %}
{% load i18n %}
{% block body %}

    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 id="container">{% trans "Contact us" %}</h3>
        </div>

        <a name="top#"></a>
        <div class="col-md-8">

                <form id="contact-data" class="form-horizontal" action="" method="POST">
                    {% csrf_token %}
                    <p>
                        <label for="id_name">{% trans "Name" %}:<span class="form-error-mark" title="Field is required.">*</span></label>
                        {{ form.name|add_class:"form-control" }}
                    </p>
                    <p>
                        <label for="id_email">{% trans "Email" %}:<span class="form-error-mark" title="Field is required.">*</span></label>
                        {{ form.email|add_class:"form-control" }}
                    </p>
                    <p>
                        <label for="id_subject">{% trans "Subject" %}:<span class="form-error-mark" title="Field is required.">*</span></label>
                        {{ form.subject|add_class:"form-control" }}
                    </p>
                    <p>
                        <label for="id_comment">{% trans "Message" %}:</label>
                        {{ form.comment|add_class:"form-control" }}
                    </p>
{#                    <p>#}
{#                        <label for="id_comment">Captcha:</label>#}
{#                        {{ form.captcha }}#}
{#                    </p>#}
                    <p>
                        <label for="submit">&nbsp;</label>
                        <input type="submit" value="{% trans "Send" %}" class="btn btn-primary btn-lg">
                    </p>
                </form>

        </div>

        <div class="col-md-4">  </div>
        

        <div class="clearfix"></div>
        <br />
        <br />
      </div>
    </div>

{% endblock %}

web/templates/web/faq.html
{% extends "vitashop/base.html" %}
{% load url from future %}
{% load i18n %}
{% block body %}

    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 id="container">FAQ</h3>
        </div>

        <a name="top#"></a>
        <div class="col-md-8">
            <h4>FAQ</h4>
            <p></p>
            <p>TODO</p>

            <div class="clearfix"></div>


        </div>

        <div class="col-md-4">  </div>
        
        <div class="centerDiv"></div>
        <div class="clearfix"></div>
        <br />
        <br />
      </div>
    </div>

{% endblock %}

web/templates/web/information.html
{% extends "vitashop/base.html" %}
{% load url from future %}
{% load i18n %}
{% block body %}

    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 id="container">{% trans "Information" %}</h3>
        </div>

        <a name="top#"></a>

        <div class="col-md-12">
            <ul>
                <li><a href="#products#">{% trans "Products" %}</a></li>
                <li><a href="#vitamins#">{% trans "Vitamins" %}</a></li>
                <li><a href="#minerals#">{% trans "Minerals" %}</a></li>
                <li><a href="#calmag#">{% trans "CalMag" %}</a></li>
                <li><a href="#shipping#">{% trans "Shipping and delivery" %}</a></li>
                <li><a href="#affiliate#">{% trans "Affiliate program" %}</a></li>
                <li><a href="{% url 'bitcoin' %}">{% trans "Bitcoins" %}</a></li>
            </ul>
        </div>

        <div class="col-md-8">
            <a name="products#"></a>
            <h4>{% trans "Products - origin and quality assurance" %}</h4>
            <p>
                {% blocktrans %}All products were made in the USA. Factory is based in Clearwater, state Florida.{% endblocktrans %}
            </p>

            <a name="vitamins#"></a>

            <h4>{% trans "Vitamins" %}</h4>
            <p>{% trans "Vitamins are organic substances..." %}</p>

            <div class="clearfix"></div>

            <a name="minerals#"></a>
            <h4>{% trans "Minerals" %}</h4>
            <p>{% trans "Minerals are..." %}</p>

            <div class="clearfix"></div>

            <a name="calmag#"></a>
            <h4>{% trans "CalMag" %}</h4>
            {% trans "What is CalMag?" %}<br>
            <p>
                <b>{% blocktrans %}Calmag is Calcium-magnesium mineral drink.{% endblocktrans %}</b>
                {% trans "Calcium and magnesium are essential..." %}
            </p>

            <div class="clearfix"></div>

            <a name="shipping#"></a>
            <h4>{% trans "Shipping and Delivery" %}</h4>
            <p>{% trans "Shipping and Delivery..." %}</p>

            <div class="clearfix"></div>

            <a name="affiliate#"></a>
            <h4>{% trans "Affiliate Program" %}</h4>
            <p>{% trans "Affiliate Program..." %}</p>

        </div>

        <div class="col-md-4">  </div>
        

        <div class="clearfix"></div>
<br /><br />
      </div>
    </div>

{% endblock %}

web/templates/web/thankyou.html
{% extends "vitashop/base.html" %}
{% load url from future %}
{% load i18n %}
{% block body %}

    <div class="row">
      <div class="col-lg-12">

        <div class="centerDiv text-center">
            <br/>
            <h3>{% trans "Thank you!" %}</h3>
        </div>

        <div class="clearfix"></div>
        <br />
        <br />
      </div>
    </div>

{% endblock %}